# Reddit webapp
windowrule = match:class ^chrome-www\.reddit\.com__-Profile_1$, float on, size 760 1294, center on, workspace special:reddit

# YT Music special workspace
windowrule = match:class ^chrome-music\.youtube\.com__-Profile_1$, float on, monitor 1, size 1214 1246, center on, workspace special:ytmusic
windowrule = match:title ^YouTube Music$, float on, size 1214 1246, center on, workspace special:ytmusic

# FotMob webapp
windowrule = match:class ^chrome-www\.fotmob\.com__en-Profile_1$, float on, size 760 1294, center on, workspace special:fotmob

# Patreon webapp
windowrule = match:class ^chrome-www\.patreon\.com__home-Default$, float on, size 760 1294, center on, workspace special:Patreon

# Authenticator
windowrule = match:class ^com\.belmoussaoui\.Authenticator$, float on, size 460 294, center on

# Xpad
windowrule = match:class ^xpad$, float on, center on, pin on

#Steam
#windowrule = match:class ^steam$, float on, size 1498 1332, center on

# LocalSend
windowrule = match:class ^localsend$, float on, size 450 657, center on

# Nautilus
windowrule = match:class ^org.gnome.Nautilus$, float on, size 1183 766, center on

# Ghostty
windowrule = match:class ^com\.mitchellh\.ghostty$, size 600 600

# Timeshift
windowrule = match:class ^timeshift-gtk$, float on, center on, size 900 650

# Sound Recorder
windowrule = match:class ^org.gnome.SoundRecorder$, float on, center on, size 400 480

# Alacritty floating terminal
windowrule = match:class ^floating-terminal$, float on, center on, size 637 737

# CopyQ
windowrule = match:class ^com.github.hluk.copyq$, float on, move cursor, size 400 480

# WhatsApp special workspace
windowrule = match:class ^chrome-web\.whatsapp\.com__-Profile_1$, float on, size 1487 1213, center on, workspace special:whatsapp, opacity 1.0 0.9

# Snippet picker (Alacritty)
windowrule = match:class ^Alacritty$, match:title ^snippet-picker$, float on, size 600 400, center on

# Remmina
windowrule = match:class ^org\.remmina\.Remmina$, workspace special:remmina silent

# Snippet picker (rofi)
windowrule = match:title ^rofi - Snippet:$, float on, size 300 300, center on

# Cheese
windowrule = match:class ^org\.gnome\.Cheese$, float on, size 950 740, center on

# X (Twitter) webapp
windowrule = match:class ^chrome-x\.com__-Profile_1$, float on, size 760 1294, center on, workspace special:x, opacity 1.0 0.9

# Clipse
windowrule = match:class ^clipse$, float on, size 622 652, move cursor

# Bitwarden (Vivaldi)
windowrule = match:class ^vivaldi-stable$, match:title ^Bitwarden - Vivaldi$, float on, size 500 674, center on
